/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.item[_ngcontent-%COMP%]{color:#333}.item[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]{list-style-type:none}.item[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]{clear:both;color:inherit;display:block;font-weight:400;line-height:1.42857143;padding:3px 20px;padding-left:10px;text-decoration:none;white-space:nowrap}.item[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]:hover{background-color:#357ebd}.item.active[_ngcontent-%COMP%], .item[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]:hover{color:#fff;outline:0;text-decoration:none}.item.active[_ngcontent-%COMP%]{background-color:#428bca}'];
//# sourceMappingURL=tree-select-item.component.scss.shim.ngstyle.js.map